# RQ4

In [1]:
import json
import pandas as pd

In [4]:
Italy = pd.read_json(r"C:\Users\Nino\Desktop\events_Italy.json")
Germany = pd.read_json(r"C:\Users\Nino\Desktop\events_Germany.json")
France = pd.read_json(r"C:\Users\Nino\Desktop\events_France.json")
England = pd.read_json(r"C:\Users\Nino\Desktop\events_England.json")
Spain = pd.read_json(r"C:\Users\Nino\Desktop\events_Spain.json")

In [5]:
events = pd.concat([Italy,Germany,France,England,Spain], axis=0)

In [6]:
events

,eventId,eventName,eventSec,id,matchId,matchPeriod,playerId,positions,subEventId,subEventName,tags,teamId
0,8,Pass,2.530536,180423957,2575959,1H,8327,"[{'y': 52, 'x': 49}, {'y': 44, 'x': 43}]",85,Simple pass,[{'id': 1801}],3158
1,8,Pass,3.768418,180423958,2575959,1H,20438,"[{'y': 44, 'x': 43}, {'y': 17, 'x': 36}]",85,Simple pass,[{'id': 1801}],3158
2,7,Others on the ball,4.868265,180423959,2575959,1H,8306,"[{'y': 17, 'x': 36}, {'y': 56, 'x': 78}]",72,Touch,[],3158
3,1,Duel,8.114676,180423960,2575959,1H,8306,"[{'y': 56, 'x': 78}, {'y': 15, 'x': 64}]",11,Ground attacking duel,"[{'id': 504}, {'id': 703}, {'id': 1801}]",3158
4,1,Duel,8.647892,180423961,2575959,1H,8306,"[{'y': 15, 'x': 64}, {'y': 15, 'x': 72}]",11,Ground attacking duel,"[{'id': 503}, {'id': 703}, {'id': 1801}]",3158
5,8,Pass,10.376066,180423962,2575959,1H,8306,"[{'y': 15, 'x': 72}, {'y': 25, 'x': 72}]",85,Simple pass,[{'id': 1801}],3158
6,1,Duel,10.796797,180423963,2575959,1H,8327,"[{'y': 25, 'x': 72}, {'y': 64, 'x': 82}]",11,Ground attacking duel,"[{'id': 602}, {'id': 703}, {'id': 1801}]",3158
7,1,Duel,11.527556,180423976,2575959,1H,86366,"[{'y': 85, 'x': 36}, {'y': 75, 'x': 28}]",12,Ground defending duel,"[{'id': 504}, {'id': 701}, {'id': 1802}]",3172
8,1,Duel,12.156579,180423977,2575959,1H,20404,"[{'y': 75, 'x': 28}, {'y': 36, 'x': 18}]",12,Ground defending duel,"[{'id': 601}, {'id': 701}, {'id': 1802}]",3172
9,1,Duel,12.418937,180423965,2575959,1H,8327,"[{'y': 64, 'x': 82}, {'y': 18, 'x': 62}]",11,Ground attacking duel,"[{'id': 701}, {'id': 1802}]",3158
10,8,Pass,16.240563,180423979,2575959,1H,86366,"[{'y': 82, 'x': 38}, {'y': 88, 'x': 43}]",85,Simple pass,[{'id': 1801}],3172
11,7,Others on the ball,17.251513,180423982,2575959,1H,246175,"[{'y': 88, 'x': 43}, {'y': 88, 'x': 39}]",72,Touch,[],3172
12,1,Duel,17.715422,180423967,2575959,1H,8306,"[{'y': 12, 'x': 61}, {'y': 15, 'x': 61}]",13,Ground loose ball duel,"[{'id': 703}, {'id': 1801}]",3158
13,1,Duel,17.791970,180423983,2575959,1H,246175,"[{'y': 88, 'x': 39}, {'y': 85, 'x': 39}]",13,Ground loose ball duel,"[{'id': 701}, {'id': 1802}]",3172
14,8,Pass,19.153235,180423968,2575959,1H,8306,"[{'y': 15, 'x': 61}, {'y': 15, 'x': 37}]",85,Simple pass,[{'id': 1801}],3158
15,8,Pass,20.873026,180423969,2575959,1H,20518,"[{'y': 15, 'x': 37}, {'y': 30, 'x': 41}]",85,Simple pass,[{'id': 1801}],3158
16,8,Pass,21.503835,180423970,2575959,1H,20438,"[{'y': 30, 'x': 41}, {'y': 16, 'x': 34}]",85,Simple pass,[{'id': 1801}],3158
17,8,Pass,23.201103,180423971,2575959,1H,20518,"[{'y': 16, 'x': 34}, {'y': 10, 'x': 51}]",85,Simple pass,[{'id': 1801}],3158
18,1,Duel,26.751844,180423972,2575959,1H,8306,"[{'y': 10, 'x': 51}, {'y': 13, 'x': 65}]",11,Ground attacking duel,"[{'id': 503}, {'id': 703}, {'id': 1801}]",3158
19,1,Duel,26.752540,180423984,2575959,1H,20404,"[{'y': 90, 'x': 49}, {'y': 87, 'x': 35}]",12,Ground defending duel,"[{'id': 504}, {'id': 701}, {'id': 1802}]",3172
20,8,Pass,27.700356,180423973,2575959,1H,8306,"[{'y': 13, 'x': 65}, {'y': 29, 'x': 71}]",85,Simple pass,[{'id': 1801}],3158
21,1,Duel,28.483430,180423974,2575959,1H,8327,"[{'y': 29, 'x': 71}, {'y': 27, 'x': 69}]",11,Ground attacking duel,"[{'id': 702}, {'id': 1801}]",3158
22,1,Duel,29.133186,180423985,2575959,1H,86366,"[{'y': 71, 'x': 29}, {'y': 73, 'x': 31}]",12,Ground defending duel,"[{'id': 702}, {'id': 1801}]",3172
23,1,Duel,30.060792,180423975,2575959,1H,20879,"[{'y': 27, 'x': 69}, {'y': 26, 'x': 74}]",11,Ground attacking duel,"[{'id': 703}, {'id': 1801}]",3158
24,1,Duel,31.352912,180423986,2575959,1H,86366,"[{'y': 73, 'x': 31}, {'y': 74, 'x': 26}]",12,Ground defending duel,"[{'id': 701}, {'id': 1802}]",3172
25,2,Foul,33.869510,180423987,2575959,1H,86366,"[{'y': 74, 'x': 26}, {'y': 73, 'x': 31}]",20,Foul,[],3172
26,3,Free Kick,52.956101,180423978,2575959,1H,8306,"[{'y': 18, 'x': 68}, {'y': 11, 'x': 89}]",31,Free Kick,[{'id': 1801}],3158
27,1,Duel,55.973765,180423980,2575959,1H,3475,"[{'y': 11, 'x': 89}, {'y': 13, 'x': 89}]",11,Ground attacking duel,"[{'id': 501}, {'id': 703}, {'id': 1801}]",3158
28,1,Duel,56.176830,180423992,2575959,1H,21077,"[{'y': 89, 'x': 11}, {'y': 87, 'x': 11}]",12,Ground defending duel,"[{'id': 502}, {'id': 701}, {'id': 1802}]",3172
29,8,Pass,57.313039,180423981,2575959,1H,3475,"[{'y': 13, 'x': 89}, {'y': 83, 'x': 100}]",80,Cross,"[{'id': 402}, {'id': 801}, {'id': 1802}]",3158
...,...,...,...,...,...,...,...,...,...,...,...,...
628629,1,Duel,2826.155800,253302636,2565927,2H,286994,"[{'y': 5, 'x': 36}, {'y': 11, 'x': 36}]",12,Ground defending duel,"[{'id': 504}, {'id': 1601}, {'id': 601}, {'id'...",682
628630,1,Duel,2826.959643,253302680,2565927,2H,4501,"[{'y': 95, 'x': 64}, {'y': 89, 'x': 64}]",11,Ground attacking duel,"[{'id': 503}, {'id': 602}, {'id': 703}, {'id':...",675
628631,7,Others on the ball,2829.338423,253302682,2565927,2H,4501,"[{'y': 89, 'x': 64}, {'y': 79, 'x': 75}]",70,Acceleration,[{'id': 1801}],675
628632,8,Pass,2830.558379,253302683,2565927,2H,4501,"[{'y': 79, 'x': 75}, {'y': 78, 'x': 97}]",85,Simple pass,[{'id': 1801}],675
628633,8,Pass,2832.161413,253302685,2565927,2H,4498,"[{'y': 78, 'x': 97}, {'y': 100, 'x': 100}]",80,Cross,"[{'id': 402}, {'id': 2101}, {'id': 1802}]",675
628634,7,Others on the ball,2832.512763,253302644,2565927,2H,3695,"[{'y': 28, 'x': 3}, {'y': 5, 'x': 0}]",72,Touch,[{'id': 1401}],682
628635,5,Interruption,2838.422522,253302645,2565927,2H,0,"[{'y': 5, 'x': 0}, {'y': 0, 'x': 0}]",50,Ball out of the field,[],682
628636,3,Free Kick,2853.997053,253302703,2565927,2H,14723,"[{'y': 100, 'x': 100}, {'y': 43, 'x': 88}]",30,Corner,"[{'id': 302}, {'id': 801}, {'id': 1801}]",675
628637,10,Shot,2857.346465,253302686,2565927,2H,4498,"[{'y': 43, 'x': 88}, {'y': 100, 'x': 100}]",100,Shot,"[{'id': 401}, {'id': 201}, {'id': 1212}, {'id'...",675
628638,5,Interruption,2857.454243,253302647,2565927,2H,0,"[{'y': 5, 'x': 0}, {'y': 0, 'x': 0}]",50,Ball out of the field,[],682
628639,3,Free Kick,2873.020476,253302649,2565927,2H,3486,"[{'y': 0, 'x': 0}, {'y': 16, 'x': 7}]",34,Goal kick,[],682
628640,8,Pass,2874.769542,253302650,2565927,2H,3695,"[{'y': 16, 'x': 7}, {'y': 6, 'x': 27}]",85,Simple pass,[{'id': 1801}],682
628641,8,Pass,2876.959208,253302651,2565927,2H,286994,"[{'y': 6, 'x': 27}, {'y': 4, 'x': 40}]",85,Simple pass,[{'id': 1801}],682
628642,1,Duel,2880.014550,253302653,2565927,2H,122832,"[{'y': 4, 'x': 40}, {'y': 5, 'x': 42}]",11,Ground attacking duel,"[{'id': 703}, {'id': 1801}]",682
628643,1,Duel,2880.551604,253302688,2565927,2H,4498,"[{'y': 96, 'x': 60}, {'y': 95, 'x': 58}]",12,Ground defending duel,"[{'id': 701}, {'id': 1802}]",675
628644,1,Duel,2880.965159,253302656,2565927,2H,122832,"[{'y': 5, 'x': 42}, {'y': 7, 'x': 49}]",11,Ground attacking duel,"[{'id': 701}, {'id': 1802}]",682
628645,1,Duel,2881.224312,253302689,2565927,2H,69404,"[{'y': 95, 'x': 58}, {'y': 93, 'x': 51}]",12,Ground defending duel,"[{'id': 703}, {'id': 1801}]",675
628646,1,Duel,2882.558967,253302657,2565927,2H,122832,"[{'y': 7, 'x': 49}, {'y': 5, 'x': 47}]",12,Ground defending duel,"[{'id': 701}, {'id': 1802}]",682
628647,1,Duel,2883.225650,253302691,2565927,2H,4501,"[{'y': 93, 'x': 51}, {'y': 95, 'x': 53}]",11,Ground attacking duel,"[{'id': 703}, {'id': 1801}]",675
628648,2,Foul,2885.241461,253302659,2565927,2H,122832,"[{'y': 5, 'x': 47}, {'y': 7, 'x': 49}]",20,Foul,[{'id': 1702}],682
628649,3,Free Kick,2917.139970,253302692,2565927,2H,3309,"[{'y': 92, 'x': 56}, {'y': 71, 'x': 92}]",31,Free Kick,[{'id': 1802}],675
628650,8,Pass,2925.547631,253302662,2565927,2H,3486,"[{'y': 29, 'x': 8}, {'y': 19, 'x': 14}]",81,Hand pass,[{'id': 1801}],682
628651,7,Others on the ball,2927.064747,253302664,2565927,2H,3695,"[{'y': 19, 'x': 14}, {'y': 34, 'x': 36}]",72,Touch,[],682
628652,8,Pass,2931.782904,253302665,2565927,2H,3695,"[{'y': 34, 'x': 36}, {'y': 52, 'x': 45}]",85,Simple pass,[{'id': 1801}],682
628653,7,Others on the ball,2932.188168,253302667,2565927,2H,20623,"[{'y': 52, 'x': 45}, {'y': 25, 'x': 66}]",70,Acceleration,[{'id': 1801}],682
628654,8,Pass,2939.077491,253302671,2565927,2H,20623,"[{'y': 25, 'x': 66}, {'y': 2, 'x': 88}]",85,Simple pass,[{'id': 1801}],682
628655,7,Others on the ball,2940.515560,253302673,2565927,2H,122832,"[{'y': 2, 'x': 88}, {'y': 21, 'x': 97}]",70,Acceleration,[{'id': 1801}],682
628656,8,Pass,2942.098761,253302674,2565927,2H,122832,"[{'y': 21, 'x': 97}, {'y': 26, 'x': 92}]",80,Cross,"[{'id': 401}, {'id': 1802}]",682
628657,8,Pass,2943.089232,253302698,2565927,2H,40756,"[{'y': 74, 'x': 8}, {'y': 56, 'x': 9}]",85,Simple pass,[{'id': 1801}],675
628658,7,Others on the ball,2943.668846,253302695,2565927,2H,3306,"[{'y': 56, 'x': 9}, {'y': 100, 'x': 100}]",71,Clearance,"[{'id': 1401}, {'id': 1802}]",675

since in this RQ we are just interested in "pass" events, we filter the rows that has eventId=8

In [7]:
pass_events = events[events.eventId == 8]
pass_events

,eventId,eventName,eventSec,id,matchId,matchPeriod,playerId,positions,subEventId,subEventName,tags,teamId
0,8,Pass,2.530536,180423957,2575959,1H,8327,"[{'y': 52, 'x': 49}, {'y': 44, 'x': 43}]",85,Simple pass,[{'id': 1801}],3158
1,8,Pass,3.768418,180423958,2575959,1H,20438,"[{'y': 44, 'x': 43}, {'y': 17, 'x': 36}]",85,Simple pass,[{'id': 1801}],3158
5,8,Pass,10.376066,180423962,2575959,1H,8306,"[{'y': 15, 'x': 72}, {'y': 25, 'x': 72}]",85,Simple pass,[{'id': 1801}],3158
10,8,Pass,16.240563,180423979,2575959,1H,86366,"[{'y': 82, 'x': 38}, {'y': 88, 'x': 43}]",85,Simple pass,[{'id': 1801}],3172
14,8,Pass,19.153235,180423968,2575959,1H,8306,"[{'y': 15, 'x': 61}, {'y': 15, 'x': 37}]",85,Simple pass,[{'id': 1801}],3158
15,8,Pass,20.873026,180423969,2575959,1H,20518,"[{'y': 15, 'x': 37}, {'y': 30, 'x': 41}]",85,Simple pass,[{'id': 1801}],3158
16,8,Pass,21.503835,180423970,2575959,1H,20438,"[{'y': 30, 'x': 41}, {'y': 16, 'x': 34}]",85,Simple pass,[{'id': 1801}],3158
17,8,Pass,23.201103,180423971,2575959,1H,20518,"[{'y': 16, 'x': 34}, {'y': 10, 'x': 51}]",85,Simple pass,[{'id': 1801}],3158
20,8,Pass,27.700356,180423973,2575959,1H,8306,"[{'y': 13, 'x': 65}, {'y': 29, 'x': 71}]",85,Simple pass,[{'id': 1801}],3158
29,8,Pass,57.313039,180423981,2575959,1H,3475,"[{'y': 13, 'x': 89}, {'y': 83, 'x': 100}]",80,Cross,"[{'id': 402}, {'id': 801}, {'id': 1802}]",3158
34,8,Pass,94.813038,180423997,2575959,1H,86366,"[{'y': 36, 'x': 32}, {'y': 6, 'x': 57}]",85,Simple pass,[{'id': 1801}],3172
35,8,Pass,97.794281,180423998,2575959,1H,295176,"[{'y': 6, 'x': 57}, {'y': 21, 'x': 69}]",85,Simple pass,[{'id': 1801}],3172
36,8,Pass,99.324654,180424001,2575959,1H,21077,"[{'y': 21, 'x': 69}, {'y': 12, 'x': 58}]",85,Simple pass,[{'id': 1801}],3172
37,8,Pass,101.978336,180424000,2575959,1H,49991,"[{'y': 12, 'x': 58}, {'y': 9, 'x': 81}]",86,Smart pass,[{'id': 1802}],3172
41,8,Pass,110.967192,180424007,2575959,1H,20841,"[{'y': 18, 'x': 40}, {'y': 77, 'x': 51}]",85,Simple pass,[{'id': 1801}],3172
42,8,Pass,116.701879,180424008,2575959,1H,41034,"[{'y': 77, 'x': 51}, {'y': 90, 'x': 58}]",85,Simple pass,[{'id': 1801}],3172
43,8,Pass,117.986911,180424009,2575959,1H,20404,"[{'y': 90, 'x': 58}, {'y': 71, 'x': 59}]",85,Simple pass,[{'id': 1801}],3172
44,8,Pass,118.372288,180424010,2575959,1H,41034,"[{'y': 71, 'x': 59}, {'y': 82, 'x': 69}]",85,Simple pass,[{'id': 1802}],3172
53,8,Pass,160.255226,180424015,2575959,1H,20841,"[{'y': 16, 'x': 14}, {'y': 3, 'x': 15}]",85,Simple pass,[{'id': 1801}],3172
55,8,Pass,163.195949,180424016,2575959,1H,295176,"[{'y': 3, 'x': 28}, {'y': 12, 'x': 14}]",85,Simple pass,[{'id': 1801}],3172
56,8,Pass,167.259232,180424017,2575959,1H,20841,"[{'y': 12, 'x': 14}, {'y': 83, 'x': 35}]",83,High pass,[{'id': 1802}],3172
57,8,Pass,173.754622,180424018,2575959,1H,3475,"[{'y': 17, 'x': 65}, {'y': 44, 'x': 56}]",85,Simple pass,[{'id': 1801}],3158
58,8,Pass,175.173176,180424019,2575959,1H,20438,"[{'y': 44, 'x': 56}, {'y': 37, 'x': 55}]",85,Simple pass,[{'id': 1801}],3158
59,8,Pass,178.127000,180424020,2575959,1H,20438,"[{'y': 37, 'x': 55}, {'y': 15, 'x': 32}]",82,Head pass,[{'id': 1801}],3158
60,8,Pass,181.969441,180424022,2575959,1H,3475,"[{'y': 15, 'x': 32}, {'y': 53, 'x': 13}]",85,Simple pass,[{'id': 1801}],3158
61,8,Pass,185.706491,180424023,2575959,1H,214220,"[{'y': 53, 'x': 13}, {'y': 64, 'x': 33}]",85,Simple pass,[{'id': 1801}],3158
62,8,Pass,188.436954,180424025,2575959,1H,92966,"[{'y': 64, 'x': 33}, {'y': 66, 'x': 32}]",85,Simple pass,[{'id': 1801}],3158
70,8,Pass,197.987393,180424037,2575959,1H,214220,"[{'y': 53, 'x': 7}, {'y': 76, 'x': 37}]",81,Hand pass,[{'id': 1801}],3158
71,8,Pass,201.317410,180424039,2575959,1H,114,"[{'y': 76, 'x': 37}, {'y': 90, 'x': 40}]",85,Simple pass,[{'id': 1801}],3158
72,8,Pass,203.034225,180424040,2575959,1H,23149,"[{'y': 90, 'x': 40}, {'y': 87, 'x': 24}]",85,Simple pass,[{'id': 1802}],3158
...,...,...,...,...,...,...,...,...,...,...,...,...
628579,8,Pass,2690.093773,253302615,2565927,2H,3306,"[{'y': 42, 'x': 31}, {'y': 50, 'x': 25}]",85,Simple pass,[{'id': 1801}],675
628581,8,Pass,2693.158074,253302616,2565927,2H,3306,"[{'y': 38, 'x': 27}, {'y': 63, 'x': 19}]",85,Simple pass,[{'id': 1801}],675
628583,8,Pass,2699.050573,253302624,2565927,2H,3309,"[{'y': 73, 'x': 45}, {'y': 72, 'x': 56}]",85,Simple pass,[{'id': 1801}],675
628586,8,Pass,2700.781421,253302597,2565927,2H,122832,"[{'y': 8, 'x': 45}, {'y': 39, 'x': 28}]",85,Simple pass,[{'id': 1801}],682
628587,8,Pass,2701.561538,253302598,2565927,2H,3695,"[{'y': 39, 'x': 28}, {'y': 10, 'x': 33}]",85,Simple pass,[{'id': 1801}],682
628588,8,Pass,2703.207109,253302599,2565927,2H,286994,"[{'y': 10, 'x': 33}, {'y': 53, 'x': 8}]",85,Simple pass,[{'id': 1801}],682
628589,8,Pass,2708.283680,253302601,2565927,2H,3486,"[{'y': 53, 'x': 8}, {'y': 74, 'x': 63}]",84,Launch,[{'id': 1802}],682
628590,8,Pass,2711.313988,253302634,2565927,2H,3306,"[{'y': 26, 'x': 37}, {'y': 13, 'x': 54}]",82,Head pass,"[{'id': 1401}, {'id': 1802}]",675
628592,8,Pass,2713.765334,253302635,2565927,2H,3310,"[{'y': 8, 'x': 56}, {'y': 0, 'x': 56}]",85,Simple pass,[{'id': 1802}],675
628595,8,Pass,2721.203942,253302639,2565927,2H,8278,"[{'y': 14, 'x': 83}, {'y': 30, 'x': 82}]",85,Simple pass,"[{'id': 302}, {'id': 1801}]",675
628613,8,Pass,2776.189218,253302623,2565927,2H,20393,"[{'y': 74, 'x': 24}, {'y': 41, 'x': 29}]",85,Simple pass,[{'id': 1801}],682
628614,8,Pass,2782.099866,253302625,2565927,2H,3695,"[{'y': 41, 'x': 29}, {'y': 66, 'x': 28}]",85,Simple pass,[{'id': 1801}],682
628616,8,Pass,2787.630183,253302628,2565927,2H,267134,"[{'y': 66, 'x': 45}, {'y': 69, 'x': 23}]",85,Simple pass,[{'id': 1801}],682
628617,8,Pass,2789.455395,253302629,2565927,2H,20393,"[{'y': 69, 'x': 23}, {'y': 90, 'x': 26}]",85,Simple pass,[{'id': 1801}],682
628618,8,Pass,2791.610988,253302630,2565927,2H,3529,"[{'y': 90, 'x': 26}, {'y': 93, 'x': 42}]",85,Simple pass,[{'id': 1801}],682
628623,8,Pass,2808.463744,253302669,2565927,2H,3306,"[{'y': 11, 'x': 37}, {'y': 27, 'x': 36}]",85,Simple pass,[{'id': 1801}],675
628624,8,Pass,2813.117759,253302672,2565927,2H,14723,"[{'y': 27, 'x': 36}, {'y': 90, 'x': 33}]",83,High pass,[{'id': 1801}],675
628625,8,Pass,2817.686043,253302675,2565927,2H,4501,"[{'y': 90, 'x': 33}, {'y': 94, 'x': 45}]",85,Simple pass,[{'id': 1801}],675
628626,8,Pass,2820.002123,253302677,2565927,2H,4498,"[{'y': 94, 'x': 45}, {'y': 90, 'x': 55}]",85,Simple pass,[{'id': 1801}],675
628627,8,Pass,2824.595914,253302678,2565927,2H,69404,"[{'y': 90, 'x': 55}, {'y': 82, 'x': 54}]",85,Simple pass,[{'id': 1801}],675
628628,8,Pass,2825.590369,253302679,2565927,2H,4498,"[{'y': 82, 'x': 54}, {'y': 95, 'x': 64}]",85,Simple pass,[{'id': 1801}],675
628632,8,Pass,2830.558379,253302683,2565927,2H,4501,"[{'y': 79, 'x': 75}, {'y': 78, 'x': 97}]",85,Simple pass,[{'id': 1801}],675
628633,8,Pass,2832.161413,253302685,2565927,2H,4498,"[{'y': 78, 'x': 97}, {'y': 100, 'x': 100}]",80,Cross,"[{'id': 402}, {'id': 2101}, {'id': 1802}]",675
628640,8,Pass,2874.769542,253302650,2565927,2H,3695,"[{'y': 16, 'x': 7}, {'y': 6, 'x': 27}]",85,Simple pass,[{'id': 1801}],682
628641,8,Pass,2876.959208,253302651,2565927,2H,286994,"[{'y': 6, 'x': 27}, {'y': 4, 'x': 40}]",85,Simple pass,[{'id': 1801}],682
628650,8,Pass,2925.547631,253302662,2565927,2H,3486,"[{'y': 29, 'x': 8}, {'y': 19, 'x': 14}]",81,Hand pass,[{'id': 1801}],682
628652,8,Pass,2931.782904,253302665,2565927,2H,3695,"[{'y': 34, 'x': 36}, {'y': 52, 'x': 45}]",85,Simple pass,[{'id': 1801}],682
628654,8,Pass,2939.077491,253302671,2565927,2H,20623,"[{'y': 25, 'x': 66}, {'y': 2, 'x': 88}]",85,Simple pass,[{'id': 1801}],682
628656,8,Pass,2942.098761,253302674,2565927,2H,122832,"[{'y': 21, 'x': 97}, {'y': 26, 'x': 92}]",80,Cross,"[{'id': 401}, {'id': 1802}]",682
628657,8,Pass,2943.089232,253302698,2565927,2H,40756,"[{'y': 74, 'x': 8}, {'y': 56, 'x': 9}]",85,Simple pass,[{'id': 1801}],675

Now we want to know about accurate passes so we filter rows that contain tag id 1801

In [9]:
acc_passes = pass_events[pass_events['tags'].apply(lambda x: pd.Series([dict['id'] for dict in x]).eq(1801).any())]

In [10]:
acc_passes

,eventId,eventName,eventSec,id,matchId,matchPeriod,playerId,positions,subEventId,subEventName,tags,teamId
0,8,Pass,2.530536,180423957,2575959,1H,8327,"[{'y': 52, 'x': 49}, {'y': 44, 'x': 43}]",85,Simple pass,[{'id': 1801}],3158
1,8,Pass,3.768418,180423958,2575959,1H,20438,"[{'y': 44, 'x': 43}, {'y': 17, 'x': 36}]",85,Simple pass,[{'id': 1801}],3158
5,8,Pass,10.376066,180423962,2575959,1H,8306,"[{'y': 15, 'x': 72}, {'y': 25, 'x': 72}]",85,Simple pass,[{'id': 1801}],3158
10,8,Pass,16.240563,180423979,2575959,1H,86366,"[{'y': 82, 'x': 38}, {'y': 88, 'x': 43}]",85,Simple pass,[{'id': 1801}],3172
14,8,Pass,19.153235,180423968,2575959,1H,8306,"[{'y': 15, 'x': 61}, {'y': 15, 'x': 37}]",85,Simple pass,[{'id': 1801}],3158
15,8,Pass,20.873026,180423969,2575959,1H,20518,"[{'y': 15, 'x': 37}, {'y': 30, 'x': 41}]",85,Simple pass,[{'id': 1801}],3158
16,8,Pass,21.503835,180423970,2575959,1H,20438,"[{'y': 30, 'x': 41}, {'y': 16, 'x': 34}]",85,Simple pass,[{'id': 1801}],3158
17,8,Pass,23.201103,180423971,2575959,1H,20518,"[{'y': 16, 'x': 34}, {'y': 10, 'x': 51}]",85,Simple pass,[{'id': 1801}],3158
20,8,Pass,27.700356,180423973,2575959,1H,8306,"[{'y': 13, 'x': 65}, {'y': 29, 'x': 71}]",85,Simple pass,[{'id': 1801}],3158
34,8,Pass,94.813038,180423997,2575959,1H,86366,"[{'y': 36, 'x': 32}, {'y': 6, 'x': 57}]",85,Simple pass,[{'id': 1801}],3172
35,8,Pass,97.794281,180423998,2575959,1H,295176,"[{'y': 6, 'x': 57}, {'y': 21, 'x': 69}]",85,Simple pass,[{'id': 1801}],3172
36,8,Pass,99.324654,180424001,2575959,1H,21077,"[{'y': 21, 'x': 69}, {'y': 12, 'x': 58}]",85,Simple pass,[{'id': 1801}],3172
41,8,Pass,110.967192,180424007,2575959,1H,20841,"[{'y': 18, 'x': 40}, {'y': 77, 'x': 51}]",85,Simple pass,[{'id': 1801}],3172
42,8,Pass,116.701879,180424008,2575959,1H,41034,"[{'y': 77, 'x': 51}, {'y': 90, 'x': 58}]",85,Simple pass,[{'id': 1801}],3172
43,8,Pass,117.986911,180424009,2575959,1H,20404,"[{'y': 90, 'x': 58}, {'y': 71, 'x': 59}]",85,Simple pass,[{'id': 1801}],3172
53,8,Pass,160.255226,180424015,2575959,1H,20841,"[{'y': 16, 'x': 14}, {'y': 3, 'x': 15}]",85,Simple pass,[{'id': 1801}],3172
55,8,Pass,163.195949,180424016,2575959,1H,295176,"[{'y': 3, 'x': 28}, {'y': 12, 'x': 14}]",85,Simple pass,[{'id': 1801}],3172
57,8,Pass,173.754622,180424018,2575959,1H,3475,"[{'y': 17, 'x': 65}, {'y': 44, 'x': 56}]",85,Simple pass,[{'id': 1801}],3158
58,8,Pass,175.173176,180424019,2575959,1H,20438,"[{'y': 44, 'x': 56}, {'y': 37, 'x': 55}]",85,Simple pass,[{'id': 1801}],3158
59,8,Pass,178.127000,180424020,2575959,1H,20438,"[{'y': 37, 'x': 55}, {'y': 15, 'x': 32}]",82,Head pass,[{'id': 1801}],3158
60,8,Pass,181.969441,180424022,2575959,1H,3475,"[{'y': 15, 'x': 32}, {'y': 53, 'x': 13}]",85,Simple pass,[{'id': 1801}],3158
61,8,Pass,185.706491,180424023,2575959,1H,214220,"[{'y': 53, 'x': 13}, {'y': 64, 'x': 33}]",85,Simple pass,[{'id': 1801}],3158
62,8,Pass,188.436954,180424025,2575959,1H,92966,"[{'y': 64, 'x': 33}, {'y': 66, 'x': 32}]",85,Simple pass,[{'id': 1801}],3158
70,8,Pass,197.987393,180424037,2575959,1H,214220,"[{'y': 53, 'x': 7}, {'y': 76, 'x': 37}]",81,Hand pass,[{'id': 1801}],3158
71,8,Pass,201.317410,180424039,2575959,1H,114,"[{'y': 76, 'x': 37}, {'y': 90, 'x': 40}]",85,Simple pass,[{'id': 1801}],3158
74,8,Pass,207.542734,180424045,2575959,1H,44251,"[{'y': 74, 'x': 12}, {'y': 79, 'x': 30}]",85,Simple pass,"[{'id': 1401}, {'id': 1801}]",3158
75,8,Pass,210.057782,180424047,2575959,1H,114,"[{'y': 79, 'x': 30}, {'y': 77, 'x': 32}]",85,Simple pass,[{'id': 1801}],3158
76,8,Pass,213.785432,180424049,2575959,1H,20879,"[{'y': 77, 'x': 32}, {'y': 74, 'x': 72}]",85,Simple pass,[{'id': 1801}],3158
84,8,Pass,237.518669,180424061,2575959,1H,8327,"[{'y': 26, 'x': 71}, {'y': 29, 'x': 64}]",85,Simple pass,[{'id': 1801}],3158
85,8,Pass,238.671690,180424064,2575959,1H,3475,"[{'y': 29, 'x': 64}, {'y': 37, 'x': 64}]",85,Simple pass,[{'id': 1801}],3158
...,...,...,...,...,...,...,...,...,...,...,...,...
628561,8,Pass,2579.699474,253302587,2565927,2H,8278,"[{'y': 33, 'x': 38}, {'y': 53, 'x': 26}]",85,Simple pass,[{'id': 1801}],675
628562,8,Pass,2586.089687,253302589,2565927,2H,3306,"[{'y': 53, 'x': 26}, {'y': 91, 'x': 26}]",85,Simple pass,[{'id': 1801}],675
628563,8,Pass,2589.275233,253302590,2565927,2H,3309,"[{'y': 91, 'x': 26}, {'y': 78, 'x': 26}]",85,Simple pass,[{'id': 1801}],675
628564,8,Pass,2593.265012,253302592,2565927,2H,4498,"[{'y': 78, 'x': 26}, {'y': 30, 'x': 26}]",83,High pass,"[{'id': 2001}, {'id': 1801}]",675
628573,8,Pass,2676.889159,253302610,2565927,2H,14723,"[{'y': 25, 'x': 14}, {'y': 9, 'x': 11}]",85,Simple pass,[{'id': 1801}],675
628579,8,Pass,2690.093773,253302615,2565927,2H,3306,"[{'y': 42, 'x': 31}, {'y': 50, 'x': 25}]",85,Simple pass,[{'id': 1801}],675
628581,8,Pass,2693.158074,253302616,2565927,2H,3306,"[{'y': 38, 'x': 27}, {'y': 63, 'x': 19}]",85,Simple pass,[{'id': 1801}],675
628583,8,Pass,2699.050573,253302624,2565927,2H,3309,"[{'y': 73, 'x': 45}, {'y': 72, 'x': 56}]",85,Simple pass,[{'id': 1801}],675
628586,8,Pass,2700.781421,253302597,2565927,2H,122832,"[{'y': 8, 'x': 45}, {'y': 39, 'x': 28}]",85,Simple pass,[{'id': 1801}],682
628587,8,Pass,2701.561538,253302598,2565927,2H,3695,"[{'y': 39, 'x': 28}, {'y': 10, 'x': 33}]",85,Simple pass,[{'id': 1801}],682
628588,8,Pass,2703.207109,253302599,2565927,2H,286994,"[{'y': 10, 'x': 33}, {'y': 53, 'x': 8}]",85,Simple pass,[{'id': 1801}],682
628595,8,Pass,2721.203942,253302639,2565927,2H,8278,"[{'y': 14, 'x': 83}, {'y': 30, 'x': 82}]",85,Simple pass,"[{'id': 302}, {'id': 1801}]",675
628613,8,Pass,2776.189218,253302623,2565927,2H,20393,"[{'y': 74, 'x': 24}, {'y': 41, 'x': 29}]",85,Simple pass,[{'id': 1801}],682
628614,8,Pass,2782.099866,253302625,2565927,2H,3695,"[{'y': 41, 'x': 29}, {'y': 66, 'x': 28}]",85,Simple pass,[{'id': 1801}],682
628616,8,Pass,2787.630183,253302628,2565927,2H,267134,"[{'y': 66, 'x': 45}, {'y': 69, 'x': 23}]",85,Simple pass,[{'id': 1801}],682
628617,8,Pass,2789.455395,253302629,2565927,2H,20393,"[{'y': 69, 'x': 23}, {'y': 90, 'x': 26}]",85,Simple pass,[{'id': 1801}],682
628618,8,Pass,2791.610988,253302630,2565927,2H,3529,"[{'y': 90, 'x': 26}, {'y': 93, 'x': 42}]",85,Simple pass,[{'id': 1801}],682
628623,8,Pass,2808.463744,253302669,2565927,2H,3306,"[{'y': 11, 'x': 37}, {'y': 27, 'x': 36}]",85,Simple pass,[{'id': 1801}],675
628624,8,Pass,2813.117759,253302672,2565927,2H,14723,"[{'y': 27, 'x': 36}, {'y': 90, 'x': 33}]",83,High pass,[{'id': 1801}],675
628625,8,Pass,2817.686043,253302675,2565927,2H,4501,"[{'y': 90, 'x': 33}, {'y': 94, 'x': 45}]",85,Simple pass,[{'id': 1801}],675
628626,8,Pass,2820.002123,253302677,2565927,2H,4498,"[{'y': 94, 'x': 45}, {'y': 90, 'x': 55}]",85,Simple pass,[{'id': 1801}],675
628627,8,Pass,2824.595914,253302678,2565927,2H,69404,"[{'y': 90, 'x': 55}, {'y': 82, 'x': 54}]",85,Simple pass,[{'id': 1801}],675
628628,8,Pass,2825.590369,253302679,2565927,2H,4498,"[{'y': 82, 'x': 54}, {'y': 95, 'x': 64}]",85,Simple pass,[{'id': 1801}],675
628632,8,Pass,2830.558379,253302683,2565927,2H,4501,"[{'y': 79, 'x': 75}, {'y': 78, 'x': 97}]",85,Simple pass,[{'id': 1801}],675
628640,8,Pass,2874.769542,253302650,2565927,2H,3695,"[{'y': 16, 'x': 7}, {'y': 6, 'x': 27}]",85,Simple pass,[{'id': 1801}],682
628641,8,Pass,2876.959208,253302651,2565927,2H,286994,"[{'y': 6, 'x': 27}, {'y': 4, 'x': 40}]",85,Simple pass,[{'id': 1801}],682
628650,8,Pass,2925.547631,253302662,2565927,2H,3486,"[{'y': 29, 'x': 8}, {'y': 19, 'x': 14}]",81,Hand pass,[{'id': 1801}],682
628652,8,Pass,2931.782904,253302665,2565927,2H,3695,"[{'y': 34, 'x': 36}, {'y': 52, 'x': 45}]",85,Simple pass,[{'id': 1801}],682
628654,8,Pass,2939.077491,253302671,2565927,2H,20623,"[{'y': 25, 'x': 66}, {'y': 2, 'x': 88}]",85,Simple pass,[{'id': 1801}],682
628657,8,Pass,2943.089232,253302698,2565927,2H,40756,"[{'y': 74, 'x': 8}, {'y': 56, 'x': 9}]",85,Simple pass,[{'id': 1801}],675

In [15]:
ratio = ( acc_passes["playerId"].value_counts() / pass_events["playerId"].value_counts() ).sort_values(ascending=[False])
ratio

568583    1.000000
257752    1.000000
22053     1.000000
472696    1.000000
472194    1.000000
400564    1.000000
20972     1.000000
415747    1.000000
461671    1.000000
286823    1.000000
15254     1.000000
291528    1.000000
329026    1.000000
331913    1.000000
337656    1.000000
339812    1.000000
342088    1.000000
447538    1.000000
447254    1.000000
352985    1.000000
353241    1.000000
354470    1.000000
357992    1.000000
360778    1.000000
364640    1.000000
364641    1.000000
423162    1.000000
397030    1.000000
367391    1.000000
391551    1.000000
            ...
375771    0.541667
399514    0.529412
99437     0.504202
8566      0.500000
15201     0.500000
272436    0.500000
294697    0.500000
8752      0.500000
426704    0.500000
13745     0.500000
37959     0.500000
279721    0.500000
365707    0.500000
301016    0.500000
26378     0.500000
18728     0.500000
26006     0.473684
404285    0.470588
6363      0.470588
272234    0.454545
248632    0.428571
15095     0.416667
14992     0.400000
257006    0.400000
500200    0.333333
363648    0.333333
297258    0.333333
223546    0.285714
342194         NaN
382289         NaN
Name: playerId, Length: 2565, dtype: float64

As you can see some of our rows have value 1. lets evaluate one of this points :

In [18]:
print(acc_passes["playerId" ].value_counts()[568583])
print(pass_events["playerId" ].value_counts()[568583])

3
3

This player had only 3 passes and all of them were accurate so we can't judge whether he is a good palyer or not based on this information. Now we put a threshhold to solve this problem. for setting a threshold, it's good to have an initial understanding of our data:

In [20]:
pass_events["playerId"].value_counts().describe()

count    2565.000000
mean      610.275244
std       524.822133
min         1.000000
25%       161.000000
50%       496.000000
75%       926.000000
max      3118.000000
Name: playerId, dtype: float64

As you can see the first quartile is 161 and it means that 75% of our population had more than 161 passes. I put this number as threshold :